CREATE TABLE tbl_localizacao (
    id_localizacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude       NUMBER(9, 6) NOT NULL,
    longitude      NUMBER(9, 6) NOT NULL,
    bairro         VARCHAR2(50) NOT NULL,
    cidade         VARCHAR2(30) NOT NULL,
    estado         VARCHAR2(2) NOT NULL,
    cep            VARCHAR2(10) NOT NULL
);

CREATE TABLE tbl_usuario (
    id_usuario     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR2(100) NOT NULL UNIQUE,
    senha          VARCHAR2(20) NOT NULL,
    tipo_usuario   VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('cidadao', 'operador', 'admin'))
);

CREATE TABLE tbl_perfil (
    id_perfil              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tbl_usuario_id_usuario NUMBER NOT NULL UNIQUE,
    nome_completo          VARCHAR2(100) NOT NULL,
    endereco               VARCHAR2(200) NOT NULL,
    telefone_pessoal       VARCHAR2(20) NOT NULL,
    telefone_emergencia    VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_perfil_usuario FOREIGN KEY (tbl_usuario_id_usuario) REFERENCES tbl_usuario(id_usuario)
);

CREATE TABLE tbl_abrigo (
    id_abrigo                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                           VARCHAR2(100) NOT NULL,
    capacidade                     NUMBER NOT NULL,
    disponivel                     CHAR(1) NOT NULL,
    tbl_localizacao_id_localizacao NUMBER NOT NULL,
    CONSTRAINT fk_abrigo_localizacao FOREIGN KEY (tbl_localizacao_id_localizacao) REFERENCES tbl_localizacao(id_localizacao)
);

CREATE TABLE tbl_sensor_iot (
    id_sensor                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_sensor                    VARCHAR2(50) NOT NULL,
    modelo                         VARCHAR2(50) NOT NULL,
    localizacao                    VARCHAR2(150) NOT NULL,
    tbl_localizacao_id_localizacao NUMBER NOT NULL,
    CONSTRAINT chk_tipo_sensor CHECK (tipo_sensor IN ('UMIDADE', 'NIVEL', 'IMAGEM')),
    CONSTRAINT fk_sensor_localizacao FOREIGN KEY (tbl_localizacao_id_localizacao) REFERENCES tbl_localizacao(id_localizacao)
);

CREATE TABLE tbl_alerta (
    id_alerta                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem                       VARCHAR2(300) NOT NULL,
    data_emissao                   DATE NOT NULL,
    nivel_alerta                   VARCHAR2(20) NOT NULL,
    tbl_usuario_id_usuario         NUMBER NOT NULL,
    tbl_localizacao_id_localizacao NUMBER NOT NULL,
    CONSTRAINT chk_nivel_alerta CHECK (nivel_alerta IN ('BAIXO', 'M�DIO', 'ALTO')),
    CONSTRAINT fk_alerta_usuario FOREIGN KEY (tbl_usuario_id_usuario) REFERENCES tbl_usuario(id_usuario),
    CONSTRAINT fk_alerta_localizacao FOREIGN KEY (tbl_localizacao_id_localizacao) REFERENCES tbl_localizacao(id_localizacao)
);

CREATE TABLE tbl_leitura_sensor (
    id_leitura               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora                DATE NOT NULL,
    valor                    NUMBER(10, 2) NOT NULL,
    tbl_sensor_iot_id_sensor NUMBER NOT NULL,
    CONSTRAINT fk_leitura_sensor FOREIGN KEY (tbl_sensor_iot_id_sensor) REFERENCES tbl_sensor_iot(id_sensor)
);

CREATE TABLE tbl_imagem_sensor (
    id_imagem                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora                DATE NOT NULL,
    url_armazenada           VARCHAR2(300) NOT NULL,
    tbl_sensor_iot_id_sensor NUMBER NOT NULL,
    CONSTRAINT fk_imagem_sensor FOREIGN KEY (tbl_sensor_iot_id_sensor) REFERENCES tbl_sensor_iot(id_sensor)
);

CREATE TABLE tbl_ocorrencia (
    id_ocorrencia                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao                      VARCHAR2(400) NOT NULL,
    data_hora                      DATE NOT NULL,
    status                         VARCHAR2(20) NOT NULL,
    tbl_usuario_id_usuario         NUMBER NOT NULL,
    tbl_localizacao_id_localizacao NUMBER NOT NULL,
    CONSTRAINT chk_status_ocorrencia CHECK (status IN ('ABERTA', 'EM ATENDIMENTO', 'RESOLVIDA')),
    CONSTRAINT fk_ocorrencia_usuario FOREIGN KEY (tbl_usuario_id_usuario) REFERENCES tbl_usuario(id_usuario),
    CONSTRAINT fk_ocorrencia_localizacao FOREIGN KEY (tbl_localizacao_id_localizacao) REFERENCES tbl_localizacao(id_localizacao)
);

CREATE TABLE tbl_rota_segura (
    id_rota                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tempo_estimado                 NUMBER(5, 2) NOT NULL,
    bloqueada                      CHAR(1) NOT NULL,
    id_origem_localizacao          NUMBER NOT NULL,
    id_destino_localizacao         NUMBER NOT NULL,
    CONSTRAINT fk_rota_origem FOREIGN KEY (id_origem_localizacao) REFERENCES tbl_localizacao(id_localizacao),
    CONSTRAINT fk_rota_destino FOREIGN KEY (id_destino_localizacao) REFERENCES tbl_localizacao(id_localizacao)
);
